jaffle_shop:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: ZYMGLEO-DP00235
      user: DOUNDOU
      password: Doundoubalarou2026
      role: dbt_role
      warehouse: dbt_wh
      database: analytics
      schema: ci
      threads: 4